import { IGRPMenuItemArgs } from '@igrp/framework-next-types';

export const IGRP_DEFAULT_MENU: IGRPMenuItemArgs[] = [
  {
    id: 9,
    name: 'Maps',
    type: 'FOLDER',
    position: 9,
    icon: 'AppWindow',
    status: 'ACTIVE',
    target: 'INTERNAL',
    url: 'maps',
    parentId: null,
    applicationId: 1,
    resourceId: null,
  },
  {
    id: 99,
    name: 'Layers',
    type: 'FOLDER',
    position: 9,
    icon: 'AppWindow',
    status: 'ACTIVE',
    target: 'INTERNAL',
    url: 'layers',
    parentId: null,
    applicationId: 1,
    resourceId: null
  },
  {
    id: 15,
    name: 'Base Maps',
    type: 'FOLDER',
    position: 9,
    icon: 'AppWindow',
    status: 'ACTIVE',
    target: 'INTERNAL',
    url: 'basemaps',
    parentId: null,
    applicationId: 1,
    resourceId: null,
  },/* 
  {
    id: 14,
    name: 'Widgets',
    type: 'FOLDER',
    position: 9,
    icon: 'AppWindow',
    status: 'ACTIVE',
    target: 'INTERNAL',
    url: 'widgets',
    parentId: null,
    applicationId: 1,
    resourceId: null,
    createdBy: 'admin',
    createdDate: '2022-01-01T12:00:00.000Z',
    lastModifiedBy: 'admin',
    lastModifiedDate: '2022-01-01T12:00:00.000Z',
  },
  {
    id: 13,
    name: 'New Widget',
    type: 'FOLDER',
    position: 9,
    icon: 'AppWindow',
    status: 'ACTIVE',
    target: 'INTERNAL',
    url: 'widgets/new',
    parentId: null,
    applicationId: 1,
    resourceId: null,
    createdBy: 'admin',
    createdDate: '2022-01-01T12:00:00.000Z',
    lastModifiedBy: 'admin',
    lastModifiedDate: '2022-01-01T12:00:00.000Z',
  }, */
  {
    id: 2,
    name: 'Settings',
    type: 'MENU_PAGE',
    position: 1,
    icon: 'Settings2',
    status: 'ACTIVE',
    target: 'INTERNAL',
    url: '/system-settings',
    parentId: null,
    applicationId: 1,
    resourceId: null,
  },
];
